{{- if not .Values.library.persistent.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wytui-library
  namespace: {{ .Release.Namespace }}
  labels:
    app: wytui-library
spec:
  storageClassName: {{ .Values.library.persistent.storageClass }}
  accessModes:
    {{- toYaml .Values.library.persistent.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.library.persistent.size }}
{{- end }}
