apiVersion: v1
entries:
  wytui:
  - apiVersion: v2
    appVersion: latest
    created: "2026-09-15T00:01:00.061060613Z"
    description: Self-hosted web UI for yt-dlp
    digest: c5231e58ef74e94f4b53c3e6f9a5facb0cc2c474a9afbd52679b361fd6267e3e
    name: wytui
    type: application
    urls:
    - https://charts.wytui.willuhmjs.com/wytui-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: latest
    created: "2026-09-15T00:01:00.060574218Z"
    description: Self-hosted web UI for yt-dlp
    digest: 37bba96076b7ee659904b8281b6b1a1e3c2985ebd53943b9f45e87e456b00a89
    name: wytui
    type: application
    urls:
    - https://charts.wytui.willuhmjs.com/wytui-0.1.0.tgz
    version: 0.1.0
generated: "2026-09-15T00:01:00.060014457Z"
