export type BrowserCookie = {
	domain: string;
	name: string;
	value: string;
	path?: string;
	secure?: boolean;
	expirationDate?: number;
	hostOnly?: boolean;
};

const AUTH_COOKIE_NAMES = new Set(['SAPISID', '__Secure-3PAPISID', 'SID', '__Secure-3PSID']);

/** Serialize browser cookies to a Netscape cookies.txt string yt-dlp accepts. */
export function cookiesToNetscape(cookies: BrowserCookie[]): string {
	const lines = ['# Netscape HTTP Cookie File', '# Generated by wytui', ''];
	for (const c of cookies) {
		const domain = c.domain.startsWith('.') ? c.domain : `.${c.domain}`;
		const includeSub = c.hostOnly ? 'FALSE' : 'TRUE';
		const path = c.path || '/';
		const secure = c.secure ? 'TRUE' : 'FALSE';
		const expiry = c.expirationDate ? String(Math.floor(c.expirationDate)) : '0';
		lines.push([domain, includeSub, path, secure, expiry, c.name, c.value].join('\t'));
	}
	return lines.join('\n') + '\n';
}

/** Heuristic: does this cookie set include YouTube/Google auth cookies? */
export function looksLikeYouTubeAuth(cookies: BrowserCookie[]): boolean {
	return cookies.some((c) => AUTH_COOKIE_NAMES.has(c.name));
}
