{{- if not .Values.secret.existing }}
{{- $authSecret := .Values.secret.authSecret -}}
{{- if not $authSecret -}}
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace .Values.secret.name) -}}
  {{- if $existingSecret -}}
    {{- $authSecret = index $existingSecret.data .Values.secret.authSecretKey | b64dec -}}
  {{- else -}}
    {{- $authSecret = randAlphaNum 64 -}}
  {{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- if not .Values.postgresql.secret.existing }}
  {{ .Values.postgresql.secret.urlKey }}: {{ include "wytui.databaseUrl" . | quote }}
  {{- end }}
  {{ .Values.secret.authSecretKey }}: {{ $authSecret | quote }}
{{- end }}
---
{{- if and .Values.oidc.enabled (not .Values.oidc.secret.existing) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oidc.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.oidc.secret.clientIdKey }}: {{ .Values.oidc.secret.clientId | quote }}
  {{ .Values.oidc.secret.clientSecretKey }}: {{ .Values.oidc.secret.clientSecret | quote }}
  {{ .Values.oidc.secret.issuerKey }}: {{ .Values.oidc.secret.issuer | quote }}
{{- end }}
